### ISSUE TITLE
twisted max line receiver line length

### ISSUE THREAD

**Issue by tobixx** [calston/riakasaurus#9]
Hi Colin,

as you may know there is a default line size limit  defined as a class attribute on the LineReceiver (16k)
Due to the indirect use of it through twisted.web, this limits hits also riakasaurus. 
And in reality at least me ;-) .

As noted in http://lists.basho.com/pipermail/riak-users_lists.basho.com/2011-February/003283.html riaks limit is practical around 64MB.

I fixed the problem in my own client like below:

```
from twisted.protocols.basic import LineReceiver 
LineReceiver.MAX_LENGTH = 1024*1024*64 
```

I would suggest to include this setting into util.py to raise the limit in riakasaurus itself.

Greetings

Steffen

**Comment by calston** [comment]
util.py stuff is going away, new Riakasaurus uses a Transport to re-align it with the riak-python-client codebase. RiakSearch is still a bit humped for some reason, so it's using old util for now.
